[2022-07-08 19:05:08 +0300] [62014] [INFO] Starting gunicorn 20.1.0
[2022-07-08 19:05:08 +0300] [62014] [INFO] Listening at: http://127.0.0.1:8000 (62014)
[2022-07-08 19:05:08 +0300] [62014] [INFO] Using worker: sync
[2022-07-08 19:05:08 +0300] [62015] [INFO] Booting worker with pid: 62015
[2022-07-08 19:05:08 +0300] [62016] [INFO] Booting worker with pid: 62016
[2022-07-08 19:05:08 +0300] [62018] [INFO] Booting worker with pid: 62018
[2022-07-08 19:05:14 +0300] [62014] [INFO] Handling signal: int
[2022-07-08 19:05:15 +0300] [62015] [INFO] Worker exiting (pid: 62015)
[2022-07-08 19:05:15 +0300] [62016] [INFO] Worker exiting (pid: 62016)
[2022-07-08 19:05:15 +0300] [62018] [INFO] Worker exiting (pid: 62018)
[2022-07-08 19:05:15 +0300] [62014] [INFO] Shutting down: Master
[2022-07-08 19:05:33 +0300] [62028] [INFO] Starting gunicorn 20.1.0
[2022-07-08 19:05:33 +0300] [62028] [INFO] Listening at: http://127.0.0.1:8000 (62028)
[2022-07-08 19:05:33 +0300] [62028] [INFO] Using worker: sync
[2022-07-08 19:05:33 +0300] [62029] [INFO] Booting worker with pid: 62029
[2022-07-08 19:05:33 +0300] [62030] [INFO] Booting worker with pid: 62030
[2022-07-08 19:05:33 +0300] [62031] [INFO] Booting worker with pid: 62031
[2022-07-08 19:12:39 +0300] [64611] [INFO] Starting gunicorn 20.1.0
[2022-07-08 19:12:39 +0300] [64611] [ERROR] Connection in use: ('127.0.0.1', 8000)
[2022-07-08 19:12:39 +0300] [64611] [ERROR] Retrying in 1 second.
[2022-07-08 19:12:40 +0300] [64611] [ERROR] Connection in use: ('127.0.0.1', 8000)
[2022-07-08 19:12:40 +0300] [64611] [ERROR] Retrying in 1 second.
[2022-07-08 19:12:41 +0300] [64611] [ERROR] Connection in use: ('127.0.0.1', 8000)
[2022-07-08 19:12:41 +0300] [64611] [ERROR] Retrying in 1 second.
[2022-07-08 19:12:43 +0300] [64611] [ERROR] Connection in use: ('127.0.0.1', 8000)
[2022-07-08 19:12:43 +0300] [64611] [ERROR] Retrying in 1 second.
[2022-07-08 19:12:44 +0300] [64611] [ERROR] Connection in use: ('127.0.0.1', 8000)
[2022-07-08 19:12:44 +0300] [64611] [ERROR] Retrying in 1 second.
[2022-07-08 19:12:45 +0300] [64611] [ERROR] Can't connect to ('127.0.0.1', 8000)
[2022-07-08 19:15:54 +0300] [62028] [INFO] Handling signal: term
[2022-07-08 19:15:54 +0300] [62030] [INFO] Worker exiting (pid: 62030)
[2022-07-08 19:15:54 +0300] [62029] [INFO] Worker exiting (pid: 62029)
[2022-07-08 19:15:54 +0300] [62031] [INFO] Worker exiting (pid: 62031)
[2022-07-08 19:15:54 +0300] [62028] [INFO] Shutting down: Master
[2022-07-08 19:17:16 +0300] [68650] [INFO] Starting gunicorn 20.1.0
[2022-07-08 19:17:16 +0300] [68650] [INFO] Listening at: http://127.0.0.1:8000 (68650)
[2022-07-08 19:17:16 +0300] [68650] [INFO] Using worker: sync
[2022-07-08 19:17:16 +0300] [68651] [INFO] Booting worker with pid: 68651
[2022-07-08 19:17:16 +0300] [68652] [INFO] Booting worker with pid: 68652
[2022-07-08 19:17:16 +0300] [68653] [INFO] Booting worker with pid: 68653
[2022-07-08 19:17:17 +0300] [68651] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/std/course-work-backend/venv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/std/course-work-backend/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/std/course-work-backend/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/std/course-work-backend/venv/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/std/course-work-backend/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/std/course-work-backend/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/std/course-work-backend/venv/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/std/course-work-backend/core/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/std/course-work-backend/venv/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/std/course-work-backend/venv/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/std/course-work-backend/venv/lib/python3.10/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/home/std/course-work-backend/venv/lib/python3.10/site-packages/django/apps/config.py", line 228, in create
    import_module(entry)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'grappelli'
[2022-07-08 19:17:17 +0300] [68651] [INFO] Worker exiting (pid: 68651)
[2022-07-08 19:17:17 +0300] [68652] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/std/course-work-backend/venv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/std/course-work-backend/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/std/course-work-backend/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/std/course-work-backend/venv/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/std/course-work-backend/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/std/course-work-backend/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/std/course-work-backend/venv/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/std/course-work-backend/core/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/std/course-work-backend/venv/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/std/course-work-backend/venv/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/std/course-work-backend/venv/lib/python3.10/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/home/std/course-work-backend/venv/lib/python3.10/site-packages/django/apps/config.py", line 228, in create
    import_module(entry)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'grappelli'
[2022-07-08 19:17:17 +0300] [68652] [INFO] Worker exiting (pid: 68652)
[2022-07-08 19:17:17 +0300] [68653] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/std/course-work-backend/venv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/std/course-work-backend/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/std/course-work-backend/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/std/course-work-backend/venv/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/std/course-work-backend/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/std/course-work-backend/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/std/course-work-backend/venv/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/std/course-work-backend/core/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/std/course-work-backend/venv/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/std/course-work-backend/venv/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/std/course-work-backend/venv/lib/python3.10/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/home/std/course-work-backend/venv/lib/python3.10/site-packages/django/apps/config.py", line 228, in create
    import_module(entry)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'grappelli'
[2022-07-08 19:17:17 +0300] [68653] [INFO] Worker exiting (pid: 68653)
[2022-07-08 19:17:17 +0300] [68650] [WARNING] Worker with pid 68653 was terminated due to signal 15
[2022-07-08 19:17:17 +0300] [68650] [WARNING] Worker with pid 68652 was terminated due to signal 15
[2022-07-08 19:17:17 +0300] [68650] [INFO] Shutting down: Master
[2022-07-08 19:17:17 +0300] [68650] [INFO] Reason: Worker failed to boot.
[2022-07-08 19:17:42 +0300] [68656] [INFO] Starting gunicorn 20.1.0
[2022-07-08 19:17:42 +0300] [68656] [INFO] Listening at: http://127.0.0.1:8000 (68656)
[2022-07-08 19:17:42 +0300] [68656] [INFO] Using worker: sync
[2022-07-08 19:17:42 +0300] [68657] [INFO] Booting worker with pid: 68657
[2022-07-08 19:17:42 +0300] [68658] [INFO] Booting worker with pid: 68658
[2022-07-08 19:17:42 +0300] [68659] [INFO] Booting worker with pid: 68659
[2022-07-08 19:17:43 +0300] [68657] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/std/course-work-backend/venv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/std/course-work-backend/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/std/course-work-backend/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/std/course-work-backend/venv/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/std/course-work-backend/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/std/course-work-backend/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/std/course-work-backend/venv/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/std/course-work-backend/core/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/std/course-work-backend/venv/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/std/course-work-backend/venv/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/std/course-work-backend/venv/lib/python3.10/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/home/std/course-work-backend/venv/lib/python3.10/site-packages/django/apps/config.py", line 228, in create
    import_module(entry)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'grappelli'
[2022-07-08 19:17:43 +0300] [68657] [INFO] Worker exiting (pid: 68657)
[2022-07-08 19:17:43 +0300] [68658] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/std/course-work-backend/venv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/std/course-work-backend/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/std/course-work-backend/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/std/course-work-backend/venv/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/std/course-work-backend/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/std/course-work-backend/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/std/course-work-backend/venv/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/std/course-work-backend/core/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/std/course-work-backend/venv/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/std/course-work-backend/venv/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/std/course-work-backend/venv/lib/python3.10/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/home/std/course-work-backend/venv/lib/python3.10/site-packages/django/apps/config.py", line 228, in create
    import_module(entry)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'grappelli'
[2022-07-08 19:17:43 +0300] [68658] [INFO] Worker exiting (pid: 68658)
[2022-07-08 19:17:43 +0300] [68659] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/std/course-work-backend/venv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/std/course-work-backend/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/std/course-work-backend/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/std/course-work-backend/venv/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/std/course-work-backend/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/std/course-work-backend/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/std/course-work-backend/venv/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/std/course-work-backend/core/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/std/course-work-backend/venv/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/std/course-work-backend/venv/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/std/course-work-backend/venv/lib/python3.10/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/home/std/course-work-backend/venv/lib/python3.10/site-packages/django/apps/config.py", line 228, in create
    import_module(entry)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'grappelli'
[2022-07-08 19:17:43 +0300] [68659] [INFO] Worker exiting (pid: 68659)
[2022-07-08 19:17:43 +0300] [68656] [WARNING] Worker with pid 68659 was terminated due to signal 15
[2022-07-08 19:17:43 +0300] [68656] [WARNING] Worker with pid 68658 was terminated due to signal 15
[2022-07-08 19:17:43 +0300] [68656] [INFO] Shutting down: Master
[2022-07-08 19:17:43 +0300] [68656] [INFO] Reason: Worker failed to boot.
[2022-07-08 20:20:36 +0300] [68775] [INFO] Starting gunicorn 20.1.0
[2022-07-08 20:20:36 +0300] [68775] [ERROR] Connection in use: ('127.0.0.1', 8000)
[2022-07-08 20:20:36 +0300] [68775] [ERROR] Retrying in 1 second.
[2022-07-08 20:20:37 +0300] [68775] [ERROR] Connection in use: ('127.0.0.1', 8000)
[2022-07-08 20:20:37 +0300] [68775] [ERROR] Retrying in 1 second.
[2022-07-08 20:20:38 +0300] [68775] [ERROR] Connection in use: ('127.0.0.1', 8000)
[2022-07-08 20:20:38 +0300] [68775] [ERROR] Retrying in 1 second.
[2022-07-08 20:20:39 +0300] [68775] [ERROR] Connection in use: ('127.0.0.1', 8000)
[2022-07-08 20:20:39 +0300] [68775] [ERROR] Retrying in 1 second.
[2022-07-08 20:20:40 +0300] [68775] [ERROR] Connection in use: ('127.0.0.1', 8000)
[2022-07-08 20:20:40 +0300] [68775] [ERROR] Retrying in 1 second.
[2022-07-08 20:20:43 +0300] [68775] [ERROR] Can't connect to ('127.0.0.1', 8000)
[2022-07-08 20:21:43 +0300] [68810] [INFO] Starting gunicorn 20.1.0
[2022-07-08 20:21:43 +0300] [68810] [ERROR] Connection in use: ('127.0.0.1', 8000)
[2022-07-08 20:21:43 +0300] [68810] [ERROR] Retrying in 1 second.
[2022-07-08 20:21:44 +0300] [68810] [ERROR] Connection in use: ('127.0.0.1', 8000)
[2022-07-08 20:21:44 +0300] [68810] [ERROR] Retrying in 1 second.
[2022-07-08 20:21:45 +0300] [68810] [ERROR] Connection in use: ('127.0.0.1', 8000)
[2022-07-08 20:21:45 +0300] [68810] [ERROR] Retrying in 1 second.
[2022-07-08 20:21:46 +0300] [68810] [ERROR] Connection in use: ('127.0.0.1', 8000)
[2022-07-08 20:21:46 +0300] [68810] [ERROR] Retrying in 1 second.
[2022-07-08 20:22:02 +0300] [68810] [ERROR] Connection in use: ('127.0.0.1', 8000)
[2022-07-08 20:22:02 +0300] [68810] [ERROR] Retrying in 1 second.
[2022-07-08 20:22:03 +0300] [68810] [ERROR] Can't connect to ('127.0.0.1', 8000)
[2022-07-08 21:58:54 +0300] [84534] [INFO] Starting gunicorn 20.1.0
[2022-07-08 21:58:54 +0300] [84534] [ERROR] Connection in use: ('127.0.0.1', 8000)
[2022-07-08 21:58:54 +0300] [84534] [ERROR] Retrying in 1 second.
[2022-07-08 21:58:55 +0300] [84534] [ERROR] Connection in use: ('127.0.0.1', 8000)
[2022-07-08 21:58:55 +0300] [84534] [ERROR] Retrying in 1 second.
[2022-07-08 21:58:56 +0300] [84534] [ERROR] Connection in use: ('127.0.0.1', 8000)
[2022-07-08 21:58:56 +0300] [84534] [ERROR] Retrying in 1 second.
[2022-07-08 21:58:57 +0300] [84534] [ERROR] Connection in use: ('127.0.0.1', 8000)
[2022-07-08 21:58:57 +0300] [84534] [ERROR] Retrying in 1 second.
[2022-07-08 21:58:58 +0300] [84534] [ERROR] Connection in use: ('127.0.0.1', 8000)
[2022-07-08 21:58:58 +0300] [84534] [ERROR] Retrying in 1 second.
[2022-07-08 21:58:59 +0300] [84534] [ERROR] Can't connect to ('127.0.0.1', 8000)
[2022-07-08 21:59:44 +0300] [84537] [INFO] Starting gunicorn 20.1.0
[2022-07-08 21:59:44 +0300] [84537] [INFO] Listening at: http://127.0.0.1:8000 (84537)
[2022-07-08 21:59:44 +0300] [84537] [INFO] Using worker: sync
[2022-07-08 21:59:44 +0300] [84538] [INFO] Booting worker with pid: 84538
[2022-07-08 21:59:44 +0300] [84539] [INFO] Booting worker with pid: 84539
[2022-07-08 21:59:44 +0300] [84540] [INFO] Booting worker with pid: 84540
Not Found: /
[2022-07-08 22:02:09 +0300] [84537] [INFO] Handling signal: hup
[2022-07-08 22:02:09 +0300] [84537] [INFO] Hang up: Master
[2022-07-08 22:02:09 +0300] [84537] [WARNING] Worker with pid 84538 was terminated due to signal 1
[2022-07-08 22:02:09 +0300] [84537] [WARNING] Worker with pid 84540 was terminated due to signal 1
[2022-07-08 22:02:09 +0300] [84537] [WARNING] Worker with pid 84539 was terminated due to signal 1
[2022-07-08 22:02:09 +0300] [84581] [INFO] Booting worker with pid: 84581
[2022-07-08 22:02:09 +0300] [84582] [INFO] Booting worker with pid: 84582
[2022-07-08 22:02:09 +0300] [84583] [INFO] Booting worker with pid: 84583
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Unauthorized: /api/auth/me/
Not Found: /undefined
Not Found: /
Unauthorized: /api/auth/me/
Unauthorized: /api/auth/me/
Not Found: /undefined
Unauthorized: /api/auth/me/
Unauthorized: /api/auth/me/
Not Found: /undefined
Unauthorized: /api/auth/me/
Not Found: /undefined
Not Found: /api/auth/login/
Unauthorized: /api/auth/me/
Not Found: /api/auth/login/
Unauthorized: /api/auth/me/
Not Found: /api/auth/login/
Unauthorized: /api/auth/me/
Unauthorized: /api/auth/me/
Unauthorized: /api/auth/me/
Unauthorized: /api/auth/me/
Not Found: /undefined
Unauthorized: /api/auth/me/
Not Found: /undefined
Unauthorized: /api/auth/me/
Not Found: /undefined
Unauthorized: /api/auth/me/
Not Found: /undefined
Unauthorized: /api/auth/me/
Unauthorized: /api/auth/me/
Not Found: /undefined
Not Found: /undefined
Unauthorized: /api/auth/me/
Unauthorized: /api/auth/me/
Unauthorized: /api/auth/me/
Not Found: /undefined
Unauthorized: /api/auth/me/
Unauthorized: /api/auth/me/
Unauthorized: /api/auth/me/
Not Found: /undefined
Unauthorized: /api/auth/me/
Unauthorized: /api/auth/me/
Unauthorized: /api/auth/me/
Unauthorized: /api/auth/me/
Unauthorized: /api/auth/me/
Unauthorized: /api/auth/me/
Unauthorized: /api/auth/me/
Unauthorized: /api/auth/me/
Unauthorized: /api/auth/me/
Unauthorized: /api/auth/me/
Unauthorized: /api/auth/me/
Unauthorized: /api/auth/me/
Unauthorized: /api/auth/me/
Not Found: /undefined
Not Found: /
Not Found: /apple-touch-icon-precomposed.png
Not Found: /apple-touch-icon.png
Not Found: /favicon.ico
Not Found: /
Not Found: /favicon.ico
Not Found: /apple-touch-icon.png
Not Found: /apple-touch-icon-precomposed.png
Not Found: /
Not Found: /favicon.ico
Unauthorized: /api/auth/me/
Unauthorized: /api/auth/me/
Unauthorized: /api/auth/me/
Unauthorized: /api/auth/me/
Not Found: /undefined
Unauthorized: /api/auth/me/
